<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Alex" ignored="0" name="Surefire test" tests="3" failures="1" timestamp="10 фев 2018 07:46:34 GMT" time="0.074" errors="0">
  <testcase name="first" time="0.008" classname="privatTests.PrivatTests"/>
  <testcase name="second" time="0.002" classname="privatTests.PrivatTests">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at privatTests.PrivatTests.second(PrivatTests.java:16)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- second -->
  <testcase name="third" time="0.0" classname="privatTests.PrivatTests"/>
</testsuite> <!-- Surefire test -->
