<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Alex" ignored="2" name="test1" tests="1" failures="1" timestamp="10 фев 2018 08:03:50 GMT" time="0.052" errors="0">
  <testcase name="second" time="0.011" classname="privatTests.PrivatTests">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at privatTests.PrivatTests.second(PrivatTests.java:16)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- second -->
  <testcase name="first" time="0.0" classname="privatTests.PrivatTests">
    <ignored/>
  </testcase> <!-- first -->
  <testcase name="third" time="0.0" classname="privatTests.PrivatTests">
    <ignored/>
  </testcase> <!-- third -->
</testsuite> <!-- test1 -->
