<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="87" started-at="2018-02-10T08:39:10Z" finished-at="2018-02-10T08:39:10Z">
    <groups>
      <group name="web">
        <method signature="PrivatTests.second()[pri:0, instance:YouTubeTest@2d209079]" name="second" class="YouTubeTest"/>
      </group> <!-- web -->
      <group name="db">
        <method signature="PrivatTests.third()[pri:0, instance:YouTubeTest@2d209079]" name="third" class="YouTubeTest"/>
      </group> <!-- db -->
    </groups>
    <test name="test2" duration-ms="8" started-at="2018-02-10T08:39:10Z" finished-at="2018-02-10T08:39:10Z">
    </test> <!-- test2 -->
    <test name="test1" duration-ms="87" started-at="2018-02-10T08:39:10Z" finished-at="2018-02-10T08:39:10Z">
      <class name="YouTubeTest">
        <test-method status="FAIL" signature="second()[pri:0, instance:YouTubeTest@2d209079]" name="second" duration-ms="26" started-at="2018-02-10T08:39:10Z" finished-at="2018-02-10T08:39:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at YouTubeTest.second(PrivatTests.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- second -->
        <test-method status="PASS" signature="third()[pri:0, instance:YouTubeTest@2d209079]" name="third" duration-ms="1" started-at="2018-02-10T08:39:10Z" finished-at="2018-02-10T08:39:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- third -->
      </class> <!-- YouTubeTest -->
    </test> <!-- test1 -->
  </suite> <!-- Suite1 -->
</testng-results>
